//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateHospitals.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrivateHospitals.Infrastructure.Resources.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &quot;AspNetUsers&quot;.&quot;Id&quot; AS DoctorId,
        ///    &quot;AspNetUsers&quot;.&quot;FirstName&quot;,
        ///    &quot;AspNetUsers&quot;.&quot;LastName&quot;,
        ///    &quot;AspNetUsers&quot;.&quot;DoctorSpeciality&quot; AS Speciality,
        ///    COUNT(&quot;Appointments&quot;.&quot;AppointmentId&quot;) AS AppointmentCount
        ///FROM &quot;AspNetUsers&quot;
        ///LEFT JOIN &quot;Appointments&quot;
        ///ON &quot;AspNetUsers&quot;.&quot;Id&quot; = &quot;Appointments&quot;.&quot;DoctorId&quot;
        ///GROUP BY &quot;AspNetUsers&quot;.&quot;Id&quot;, &quot;AspNetUsers&quot;.&quot;FirstName&quot;, &quot;AspNetUsers&quot;.&quot;LastName&quot;, &quot;AspNetUsers&quot;.&quot;DoctorSpeciality&quot;
        ///HAVING COUNT(&quot;Appointments&quot;.&quot;AppointmentId&quot;) &gt;= 1
        ///ORDER BY AppointmentCount DESC;
        ///.
        /// </summary>
        internal static string DoctorAppointmentsMoreThanOne {
            get {
                return ResourceManager.GetString("DoctorAppointmentsMoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &quot;DoctorSpeciality&quot;,
        ///    AVG(AppointmentCount) AS AvgAppointments
        ///FROM (
        ///    SELECT 
        ///        &quot;DoctorSpeciality&quot;,
        ///        COUNT(&quot;Appointments&quot;.&quot;AppointmentId&quot;) AS AppointmentCount
        ///    FROM &quot;AspNetUsers&quot;
        ///    LEFT JOIN &quot;Appointments&quot; 
        ///    ON &quot;AspNetUsers&quot;.&quot;Id&quot; = &quot;Appointments&quot;.&quot;DoctorId&quot;
        /// WHERE &quot;Role&quot; = &apos;Doctor&apos;
        ///    GROUP BY &quot;AspNetUsers&quot;.&quot;Id&quot;, &quot;DoctorSpeciality&quot;
        ///) AS DoctorAppointments
        ///GROUP BY &quot;DoctorSpeciality&quot;
        ///ORDER BY AvgAppointments DESC;.
        /// </summary>
        internal static string DoctorAvgAppointments {
            get {
                return ResourceManager.GetString("DoctorAvgAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    CASE 
        ///        WHEN &quot;DoctorSpeciality&quot; = 0 THEN &apos;Doctor&apos;
        ///        WHEN &quot;DoctorSpeciality&quot; = 1 THEN &apos;Cardiologist&apos;
        ///        WHEN &quot;DoctorSpeciality&quot; = 2 THEN &apos;Dermatologist&apos;
        ///        WHEN &quot;DoctorSpeciality&quot; = 3 THEN &apos;Neurologist&apos;
        ///        ELSE &apos;Unknown&apos;
        ///    END AS DoctorSpecialityName,
        ///    COUNT(*) AS DoctorCount
        ///FROM &quot;AspNetUsers&quot;
        ///WHERE &quot;Role&quot; = &apos;Doctor&apos;
        ///GROUP BY &quot;DoctorSpeciality&quot;
        ///ORDER BY DoctorCount DESC;
        ///.
        /// </summary>
        internal static string DoctorCountBySpeciality {
            get {
                return ResourceManager.GetString("DoctorCountBySpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EXISTS (
        ///    SELECT 1
        ///    FROM &quot;DoctorInfos&quot;
        ///    WHERE &quot;DoctorInfoId&quot; = @doctorId
        ///);.
        /// </summary>
        internal static string DoctorExists {
            get {
                return ResourceManager.GetString("DoctorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &quot;DoctorSpeciality&quot;,
        ///    &quot;YearsOfExperience&quot;,
        ///    NTILE(4) OVER (PARTITION BY &quot;DoctorSpeciality&quot; ORDER BY &quot;YearsOfExperience&quot;) AS Quartile
        ///FROM &quot;AspNetUsers&quot;
        ///WHERE &quot;Role&quot; = &apos;Doctor&apos;
        ///ORDER BY &quot;DoctorSpeciality&quot;, Quartile;
        ///.
        /// </summary>
        internal static string DoctorQuantiles {
            get {
                return ResourceManager.GetString("DoctorQuantiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    &quot;DoctorSpeciality&quot; AS Speciality,
        ///    AVG(COALESCE(&quot;YearsOfExperience&quot;, 0)) AS AverageExperience
        ///FROM &quot;AspNetUsers&quot;
        ///WHERE &quot;Role&quot; = &apos;Doctor&apos;
        ///GROUP BY &quot;DoctorSpeciality&quot;
        ///ORDER BY AverageExperience DESC;
        ///.
        /// </summary>
        internal static string DoctorYearsOfExperience {
            get {
                return ResourceManager.GetString("DoctorYearsOfExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;DoctorInfos&quot; (&quot;DoctorInfoId&quot;, &quot;FirstName&quot;, &quot;LastName&quot;, &quot;Email&quot;, &quot;University&quot;, &quot;INN&quot;, &quot;DiplomNumber&quot;)
        ///VALUES (@DoctorId, @FirstName, @LastName, @Email, @Universities, @INN, @DiplomNumber);
        ///.
        /// </summary>
        internal static string InsertDoctorInfo {
            get {
                return ResourceManager.GetString("InsertDoctorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE &quot;DoctorInfos&quot; SET
        ///    &quot;FirstName&quot; = @FirstName,
        ///    &quot;LastName&quot; = @LastName,
        ///    &quot;Email&quot; = @Email,
        ///    &quot;University&quot; = @Universities,
        ///    &quot;INN&quot; = @INN,
        ///    &quot;DiplomNumber&quot; = @DiplomNumber
        ///WHERE &quot;DoctorInfoId&quot; = @DoctorId;
        ///.
        /// </summary>
        internal static string UpdateDoctorInfo {
            get {
                return ResourceManager.GetString("UpdateDoctorInfo", resourceCulture);
            }
        }
    }
}
