name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd
  pull_request:
    branches: 
      - feature/ci-cd
 
jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0'
      
      - name: Restore dependencies
        run: dotnet restore PrivateHospitals/backend/PrivateHospitals/PrivateHospitals.sln

      - name: Build project
        run: dotnet build PrivateHospitals/backend/PrivateHospitals/PrivateHospitals.sln --no-restore

      - name: Create test results directory
        run: mkdir -p ./test-results/unit      

      - name: Run Unit Tests
        run: |
          dotnet test PrivateHospitals/backend/PrivateHospitals/PrivateHospitals.Tests/PrivateHospitals.Tests.csproj --logger "html" --results-directory ./test-results/unit

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: ./test-results/  

  docker: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t vadim112281/private-hospitals:latest -f PrivateHospitals/backend/PrivateHospitals/Dockerfile .
      
      - name: Push Docker image
        run: docker push vadim112281/private-hospitals:latest

    
  




      
  
