name: CI/CD pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd
  pull_request:
    branches: 
      - feature/ci-cd

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0'

      - name: Build project
        run: dotnet build PrivateHospitals/backend/PrivateHospitals/PrivateHospitals.sln --no-restore

  docker: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t vadim112281/private-hospitals:latest .
      
      - name: Push Docker image
        run: docker push vadim112281/private-hospitals:latest

    
  




      
  